name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - run: |
          echo 'release_created: ${{ steps.release.outputs.release_created }}'
          echo 'upload_url: ${{ steps.release.outputs.upload_url }}'
          echo 'html_url: ${{ steps.release.outputs.html_url }}'
          echo 'tag_name: ${{ steps.release.outputs.tag_name }}'
          echo 'major: ${{ steps.release.outputs.major }}'
          echo 'minor: ${{ steps.release.outputs.minor }}'
          echo 'patch: ${{ steps.release.outputs.patch }}'
          echo 'sha: ${{ steps.release.outputs.sha }}'
          echo 'pr: ${{ steps.release.outputs.pr }}'
