name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - run: |
          echo 'release_created: ${{ steps.release.outputs.releases_created }}'
          echo 'upload_url: ${{ steps.release.outputs.packages/package-a--upload_url }}'
          echo 'html_url: ${{ steps.release.outputs.packages/package-a--html_url }}'
          echo 'tag_name: ${{ steps.release.outputs.packages/package-a--tag_name }}'
          echo 'major: ${{ steps.release.outputs.packages/package-a--major }}'
          echo 'minor: ${{ steps.release.outputs.packages/package-a--minor }}'
          echo 'patch: ${{ steps.release.outputs.packages/package-a--patch }}'
          echo 'sha: ${{ steps.release.outputs.packages/package-a--sha }}'
          echo 'pr: ${{ steps.release.outputs.packages/package-a--pr }}'
          echo 'upload_url: ${{ steps.release.outputs.packages/package-b--upload_url }}'
          echo 'html_url: ${{ steps.release.outputs.packages/package-b--html_url }}'
          echo 'tag_name: ${{ steps.release.outputs.packages/package-b--tag_name }}'
          echo 'major: ${{ steps.release.outputs.packages/package-b--major }}'
          echo 'minor: ${{ steps.release.outputs.packages/package-b--minor }}'
          echo 'patch: ${{ steps.release.outputs.packages/package-b--patch }}'
          echo 'sha: ${{ steps.release.outputs.packages/package-b--sha }}'
          echo 'pr: ${{ steps.release.outputs.packages/package-b--pr }}'
          echo 'upload_url: ${{ steps.release.outputs.packages/package-c--upload_url }}'
          echo 'html_url: ${{ steps.release.outputs.packages/package-c--html_url }}'
          echo 'tag_name: ${{ steps.release.outputs.packages/package-c--tag_name }}'
          echo 'major: ${{ steps.release.outputs.packages/package-c--major }}'
          echo 'minor: ${{ steps.release.outputs.packages/package-c--minor }}'
          echo 'patch: ${{ steps.release.outputs.packages/package-c--patch }}'
          echo 'sha: ${{ steps.release.outputs.packages/package-c--sha }}'
          echo 'pr: ${{ steps.release.outputs.packages/package-c--pr }}'
